services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php8.3
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        volumes:
            - mysql-data:/var/lib/mysql/
            - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
volumes:
    mysql-data:
        driver: local
